// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfVISrKzb6tHmx7F99aa1BgHjO8iAcN2k',
    appId: '1:375902053633:web:60ed8206a7e89ccc5ce700',
    messagingSenderId: '375902053633',
    projectId: 'final-app-778f6',
    authDomain: 'final-app-778f6.firebaseapp.com',
    storageBucket: 'final-app-778f6.firebasestorage.app',
    measurementId: 'G-GXN1X04DBT',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCul6HpVUn22cfqoSI6TpJU7XHcBEAuPFw',
    appId: '1:375902053633:ios:f0116bdb74d4ee375ce700',
    messagingSenderId: '375902053633',
    projectId: 'final-app-778f6',
    storageBucket: 'final-app-778f6.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCul6HpVUn22cfqoSI6TpJU7XHcBEAuPFw',
    appId: '1:375902053633:ios:f0116bdb74d4ee375ce700',
    messagingSenderId: '375902053633',
    projectId: 'final-app-778f6',
    storageBucket: 'final-app-778f6.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfVISrKzb6tHmx7F99aa1BgHjO8iAcN2k',
    appId: '1:375902053633:web:f33f1b46590d6c395ce700',
    messagingSenderId: '375902053633',
    projectId: 'final-app-778f6',
    authDomain: 'final-app-778f6.firebaseapp.com',
    storageBucket: 'final-app-778f6.firebasestorage.app',
    measurementId: 'G-C6RFXHX1PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpqJEE_7Fcheuaj_Uj13T8YU2MK3Mvn6E',
    appId: '1:375902053633:android:09d441ad8c40f3495ce700',
    messagingSenderId: '375902053633',
    projectId: 'final-app-778f6',
    storageBucket: 'final-app-778f6.firebasestorage.app',
  );

}